### ISSUE TITLE
First Run Error !!!

### ISSUE THREAD

**Issue by dewebdes** [shiblisec/Kyubi#1]
kyubi -v http://81.88.42.184 
Traceback (most recent call last):
  File "/usr/bin/kyubi", line 33, in <module>
    sys.exit(load_entry_point('kyubi==0.1.0', 'console_scripts', 'kyubi')())
  File "/usr/bin/kyubi", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: kyubi

**Comment by shibli2700** [comment]
Hey,

Did you try installing the tool using the following command?
```
sudo python3 setup.py install
```
I did a fresh installation and was able to run it.
![image](https://user-images.githubusercontent.com/18637512/180695936-6dcef780-9a34-4b52-8250-09ccd22c3a84.png)

**Comment by saami97** [comment]
Yes, I did. Still the same.

**Comment by saami97** [comment]
This issue is resolved now. Check the installation guide for the updated steps.

**Comment by saami97** [comment]
@shiblisec :  I believe, this issue can be marked as resolved as the tool is working now based on fix #3

**Comment by shiblisec** [comment]
Resolved!!!

**Comment by saami97** [comment]
Hi @shiblisec Did we encounter any bugs for this to be reopened?
